In [32]:
import functools
import pandas as pd
import numpy as np
import seaborn as sns
from pathlib import Path
from matplotlib import pyplot as plt

In [5]:
word_list: list[str] = []
with Path("../data/word_list.txt").open() as f:
    word_list = f.read().split(' ')
if not word_list:
    print("Failed to load word list")

In [38]:
char_tuples = [
    (word, *tuple(char for char in word))
    for word in word_list
]
char_tuples

[('AAHED', 'A', 'A', 'H', 'E', 'D'),
 ('AALII', 'A', 'A', 'L', 'I', 'I'),
 ('AARGH', 'A', 'A', 'R', 'G', 'H'),
 ('AARTI', 'A', 'A', 'R', 'T', 'I'),
 ('ABACA', 'A', 'B', 'A', 'C', 'A'),
 ('ABACI', 'A', 'B', 'A', 'C', 'I'),
 ('ABACK', 'A', 'B', 'A', 'C', 'K'),
 ('ABACS', 'A', 'B', 'A', 'C', 'S'),
 ('ABAFT', 'A', 'B', 'A', 'F', 'T'),
 ('ABAKA', 'A', 'B', 'A', 'K', 'A'),
 ('ABAMP', 'A', 'B', 'A', 'M', 'P'),
 ('ABAND', 'A', 'B', 'A', 'N', 'D'),
 ('ABASE', 'A', 'B', 'A', 'S', 'E'),
 ('ABASH', 'A', 'B', 'A', 'S', 'H'),
 ('ABASK', 'A', 'B', 'A', 'S', 'K'),
 ('ABATE', 'A', 'B', 'A', 'T', 'E'),
 ('ABAYA', 'A', 'B', 'A', 'Y', 'A'),
 ('ABBAS', 'A', 'B', 'B', 'A', 'S'),
 ('ABBED', 'A', 'B', 'B', 'E', 'D'),
 ('ABBES', 'A', 'B', 'B', 'E', 'S'),
 ('ABBEY', 'A', 'B', 'B', 'E', 'Y'),
 ('ABBOT', 'A', 'B', 'B', 'O', 'T'),
 ('ABCEE', 'A', 'B', 'C', 'E', 'E'),
 ('ABEAM', 'A', 'B', 'E', 'A', 'M'),
 ('ABEAR', 'A', 'B', 'E', 'A', 'R'),
 ('ABELE', 'A', 'B', 'E', 'L', 'E'),
 ('ABERS', 'A', 'B', 'E', 'R', 'S'),
 ('ABETS', 'A', 'B', 'E', 'T', 'S'),
 ('ABHOR', 'A', 'B', 'H', 'O', 'R'),
 ('ABIDE', 'A', 'B', 'I', 'D', 'E'),
 ('ABIES', 'A', 'B', 'I', 'E', 'S'),
 ('ABLED', 'A', 'B', 'L', 'E', 'D'),
 ('ABLER', 'A', 'B', 'L', 'E', 'R'),
 ('ABLES', 'A', 'B', 'L', 'E', 'S'),
 ('ABLET', 'A', 'B', 'L', 'E', 'T'),
 ('ABLOW', 'A', 'B', 'L', 'O', 'W'),
 ('ABMHO', 'A', 'B', 'M', 'H', 'O'),
 ('ABODE', 'A', 'B', 'O', 'D', 'E'),
 ('ABOHM', 'A', 'B', 'O', 'H', 'M'),
 ('ABOIL', 'A', 'B', 'O', 'I', 'L'),
 ('ABOMA', 'A', 'B', 'O', 'M', 'A'),
 ('ABOON', 'A', 'B', 'O', 'O', 'N'),
 ('ABORD', 'A', 'B', 'O', 'R', 'D'),
 ('ABORE', 'A', 'B', 'O', 'R', 'E'),
 ('ABORT', 'A', 'B', 'O', 'R', 'T'),
 ('ABOUT', 'A', 'B', 'O', 'U', 'T'),
 ('ABOVE', 'A', 'B', 'O', 'V', 'E'),
 ('ABRAM', 'A', 'B', 'R', 'A', 'M'),
 ('ABRAY', 'A', 'B', 'R', 'A', 'Y'),
 ('ABRIM', 'A', 'B', 'R', 'I', 'M'),
 ('ABRIN', 'A', 'B', 'R', 'I', 'N'),
 ('ABRIS', 'A', 'B', 'R', 'I', 'S'),
 ('ABSEY', 'A', 'B', 'S', 'E', 'Y'),
 ('ABSIT', 'A', 'B', 'S', 'I', 'T'),
 ('ABUNA', 'A', 'B', 'U', 'N', 'A'),
 ('ABUNE', 'A', 'B', 'U', 'N', 'E'),
 ('ABUSE', 'A', 'B', 'U', 'S', 'E'),
 ('ABUTS', 'A', 'B', 'U', 'T', 'S'),
 ('ABUZZ', 'A', 'B', 'U', 'Z', 'Z'),
 ('ABYES', 'A', 'B', 'Y', 'E', 'S'),
 ('ABYSM', 'A', 'B', 'Y', 'S', 'M'),
 ('ABYSS', 'A', 'B', 'Y', 'S', 'S'),
 ('ACAIS', 'A', 'C', 'A', 'I', 'S'),
 ('ACARI', 'A', 'C', 'A', 'R', 'I'),
 ('ACCAS', 'A', 'C', 'C', 'A', 'S'),
 ('ACCOY', 'A', 'C', 'C', 'O', 'Y'),
 ('ACERB', 'A', 'C', 'E', 'R', 'B'),
 ('ACERS', 'A', 'C', 'E', 'R', 'S'),
 ('ACETA', 'A', 'C', 'E', 'T', 'A'),
 ('ACHAR', 'A', 'C', 'H', 'A', 'R'),
 ('ACHED', 'A', 'C', 'H', 'E', 'D'),
 ('ACHES', 'A', 'C', 'H', 'E', 'S'),
 ('ACHOO', 'A', 'C', 'H', 'O', 'O'),
 ('ACIDS', 'A', 'C', 'I', 'D', 'S'),
 ('ACIDY', 'A', 'C', 'I', 'D', 'Y'),
 ('ACING', 'A', 'C', 'I', 'N', 'G'),
 ('ACINI', 'A', 'C', 'I', 'N', 'I'),
 ('ACKEE', 'A', 'C', 'K', 'E', 'E'),
 ('ACKER', 'A', 'C', 'K', 'E', 'R'),
 ('ACMES', 'A', 'C', 'M', 'E', 'S'),
 ('ACMIC', 'A', 'C', 'M', 'I', 'C'),
 ('ACNED', 'A', 'C', 'N', 'E', 'D'),
 ('ACNES', 'A', 'C', 'N', 'E', 'S'),
 ('ACOCK', 'A', 'C', 'O', 'C', 'K'),
 ('ACOLD', 'A', 'C', 'O', 'L', 'D'),
 ('ACORN', 'A', 'C', 'O', 'R', 'N'),
 ('ACRED', 'A', 'C', 'R', 'E', 'D'),
 ('ACRES', 'A', 'C', 'R', 'E', 'S'),
 ('ACRID', 'A', 'C', 'R', 'I', 'D'),
 ('ACROS', 'A', 'C', 'R', 'O', 'S'),
 ('ACTED', 'A', 'C', 'T', 'E', 'D'),
 ('ACTIN', 'A', 'C', 'T', 'I', 'N'),
 ('ACTON', 'A', 'C', 'T', 'O', 'N'),
 ('ACTOR', 'A', 'C', 'T', 'O', 'R'),
 ('ACUTE', 'A', 'C', 'U', 'T', 'E'),
 ('ACYLS', 'A', 'C', 'Y', 'L', 'S'),
 ('ADAGE', 'A', 'D', 'A', 'G', 'E'),
 ('ADAPT', 'A', 'D', 'A', 'P', 'T'),
 ('ADAWS', 'A', 'D', 'A', 'W', 'S'),
 ('ADAYS', 'A', 'D', 'A', 'Y', 'S'),
 ('ADBOT', 'A', 'D', 'B', 'O', 'T'),
 ('ADDAX', 'A', 'D', 'D', 'A', 'X'),
 ('ADDED', 'A', 'D', 'D', 'E', 'D'),
 ('ADDER', 'A', 'D', 'D', 'E', 'R'),
 ('ADDIO', 'A', 'D', 'D', 'I', 'O'),
 ('ADDLE', 'A', 'D', 'D', 'L', 'E'),
 ('ADEEM', 'A', 'D', 'E', 'E', 'M'),
 ('ADEPT', 'A', 'D', 'E', 'P', 'T'),
 ('ADHAN', 'A', 'D', 'H', 'A', 'N'),
 ('ADIEU', 'A', 'D', 'I', 'E', 'U'),
 ('ADIOS', 'A', 'D', 'I', 'O', 'S'),
 ('ADITS', 'A', 'D', 'I', 'T', 'S'),
 ('ADMAN', 'A', 'D', 'M', 'A', 'N'),
 ('ADMEN', 'A', 'D', 'M', 'E', 'N'),
 ('ADMIN', 'A', 'D', 'M', 'I', 'N'),
 ('ADMIT', 'A', 'D', 'M', 'I', 'T'),
 ('ADMIX', 'A', 'D', 'M', 'I', 'X'),
 ('ADOBE', 'A', 'D', 'O', 'B', 'E'),
 ('ADOBO', 'A', 'D', 'O', 'B', 'O'),
 ('ADOPT', 'A', 'D', 'O', 'P', 'T'),
 ('ADORE', 'A', 'D', 'O', 'R', 'E'),
 ('ADORN', 'A', 'D', 'O', 'R', 'N'),
 ('ADOWN', 'A', 'D', 'O', 'W', 'N'),
 ('ADOZE', 'A', 'D', 'O', 'Z', 'E'),
 ('ADRAD', 'A', 'D', 'R', 'A', 'D'),
 ('ADRED', 'A', 'D', 'R', 'E', 'D'),
 ('ADSUM', 'A', 'D', 'S', 'U', 'M'),
 ('ADUKI', 'A', 'D', 'U', 'K', 'I'),
 ('ADULT', 'A', 'D', 'U', 'L', 'T'),
 ('ADUNC', 'A', 'D', 'U', 'N', 'C'),
 ('ADUST', 'A', 'D', 'U', 'S', 'T'),
 ('ADVEW', 'A', 'D', 'V', 'E', 'W'),
 ('ADYTA', 'A', 'D', 'Y', 'T', 'A'),
 ('ADZED', 'A', 'D', 'Z', 'E', 'D'),
 ('ADZES', 'A', 'D', 'Z', 'E', 'S'),
 ('AECIA', 'A', 'E', 'C', 'I', 'A'),
 ('AEDES', 'A', 'E', 'D', 'E', 'S'),
 ('AEGIS', 'A', 'E', 'G', 'I', 'S'),
 ('AEONS', 'A', 'E', 'O', 'N', 'S'),
 ('AERIE', 'A', 'E', 'R', 'I', 'E'),
 ('AEROS', 'A', 'E', 'R', 'O', 'S'),
 ('AESIR', 'A', 'E', 'S', 'I', 'R'),
 ('AFALD', 'A', 'F', 'A', 'L', 'D'),
 ('AFARA', 'A', 'F', 'A', 'R', 'A'),
 ('AFARS', 'A', 'F', 'A', 'R', 'S'),
 ('AFEAR', 'A', 'F', 'E', 'A', 'R'),
 ('AFFIX', 'A', 'F', 'F', 'I', 'X'),
 ('AFIRE', 'A', 'F', 'I', 'R', 'E'),
 ('AFLAJ', 'A', 'F', 'L', 'A', 'J'),
 ('AFOOT', 'A', 'F', 'O', 'O', 'T'),
 ('AFORE', 'A', 'F', 'O', 'R', 'E'),
 ('AFOUL', 'A', 'F', 'O', 'U', 'L'),
 ('AFRIT', 'A', 'F', 'R', 'I', 'T'),
 ('AFROS', 'A', 'F', 'R', 'O', 'S'),
 ('AFTER', 'A', 'F', 'T', 'E', 'R'),
 ('AGAIN', 'A', 'G', 'A', 'I', 'N'),
 ('AGAMA', 'A', 'G', 'A', 'M', 'A'),
 ('AGAMI', 'A', 'G', 'A', 'M', 'I'),
 ('AGAPE', 'A', 'G', 'A', 'P', 'E'),
 ('AGARS', 'A', 'G', 'A', 'R', 'S'),
 ('AGAST', 'A', 'G', 'A', 'S', 'T'),
 ('AGATE', 'A', 'G', 'A', 'T', 'E'),
 ('AGAVE', 'A', 'G', 'A', 'V', 'E'),
 ('AGAZE', 'A', 'G', 'A', 'Z', 'E'),
 ('AGENE', 'A', 'G', 'E', 'N', 'E'),
 ('AGENT', 'A', 'G', 'E', 'N', 'T'),
 ('AGERS', 'A', 'G', 'E', 'R', 'S'),
 ('AGGER', 'A', 'G', 'G', 'E', 'R'),
 ('AGGIE', 'A', 'G', 'G', 'I', 'E'),
 ('AGGRI', 'A', 'G', 'G', 'R', 'I'),
 ('AGGRO', 'A', 'G', 'G', 'R', 'O'),
 ('AGGRY', 'A', 'G', 'G', 'R', 'Y'),
 ('AGHAS', 'A', 'G', 'H', 'A', 'S'),
 ('AGILA', 'A', 'G', 'I', 'L', 'A'),
 ('AGILE', 'A', 'G', 'I', 'L', 'E'),
 ('AGING', 'A', 'G', 'I', 'N', 'G'),
 ('AGIOS', 'A', 'G', 'I', 'O', 'S'),
 ('AGISM', 'A', 'G', 'I', 'S', 'M'),
 ('AGIST', 'A', 'G', 'I', 'S', 'T'),
 ('AGITA', 'A', 'G', 'I', 'T', 'A'),
 ('AGLEE', 'A', 'G', 'L', 'E', 'E'),
 ('AGLET', 'A', 'G', 'L', 'E', 'T'),
 ('AGLEY', 'A', 'G', 'L', 'E', 'Y'),
 ('AGLOO', 'A', 'G', 'L', 'O', 'O'),
 ('AGLOW', 'A', 'G', 'L', 'O', 'W'),
 ('AGLUS', 'A', 'G', 'L', 'U', 'S'),
 ('AGMAS', 'A', 'G', 'M', 'A', 'S'),
 ('AGOGE', 'A', 'G', 'O', 'G', 'E'),
 ('AGONE', 'A', 'G', 'O', 'N', 'E'),
 ('AGONS', 'A', 'G', 'O', 'N', 'S'),
 ('AGONY', 'A', 'G', 'O', 'N', 'Y'),
 ('AGOOD', 'A', 'G', 'O', 'O', 'D'),
 ('AGORA', 'A', 'G', 'O', 'R', 'A'),
 ('AGREE', 'A', 'G', 'R', 'E', 'E'),
 ('AGRIA', 'A', 'G', 'R', 'I', 'A'),
 ('AGRIN', 'A', 'G', 'R', 'I', 'N'),
 ('AGROS', 'A', 'G', 'R', 'O', 'S'),
 ('AGUED', 'A', 'G', 'U', 'E', 'D'),
 ('AGUES', 'A', 'G', 'U', 'E', 'S'),
 ('AGUNA', 'A', 'G', 'U', 'N', 'A'),
 ('AGUTI', 'A', 'G', 'U', 'T', 'I'),
 ('AHEAD', 'A', 'H', 'E', 'A', 'D'),
 ('AHEAP', 'A', 'H', 'E', 'A', 'P'),
 ('AHENT', 'A', 'H', 'E', 'N', 'T'),
 ('AHIGH', 'A', 'H', 'I', 'G', 'H'),
 ('AHIND', 'A', 'H', 'I', 'N', 'D'),
 ('AHING', 'A', 'H', 'I', 'N', 'G'),
 ('AHINT', 'A', 'H', 'I', 'N', 'T'),
 ('AHOLD', 'A', 'H', 'O', 'L', 'D'),
 ('AHULL', 'A', 'H', 'U', 'L', 'L'),
 ('AHURU', 'A', 'H', 'U', 'R', 'U'),
 ('AIDAS', 'A', 'I', 'D', 'A', 'S'),
 ('AIDED', 'A', 'I', 'D', 'E', 'D'),
 ('AIDER', 'A', 'I', 'D', 'E', 'R'),
 ('AIDES', 'A', 'I', 'D', 'E', 'S'),
 ('AIDOI', 'A', 'I', 'D', 'O', 'I'),
 ('AIDOS', 'A', 'I', 'D', 'O', 'S'),
 ('AIERY', 'A', 'I', 'E', 'R', 'Y'),
 ('AIGAS', 'A', 'I', 'G', 'A', 'S'),
 ('AIGHT', 'A', 'I', 'G', 'H', 'T'),
 ('AILED', 'A', 'I', 'L', 'E', 'D'),
 ('AIMED', 'A', 'I', 'M', 'E', 'D'),
 ('AIMER', 'A', 'I', 'M', 'E', 'R'),
 ('AINEE', 'A', 'I', 'N', 'E', 'E'),
 ('AINGA', 'A', 'I', 'N', 'G', 'A'),
 ('AIOLI', 'A', 'I', 'O', 'L', 'I'),
 ('AIRED', 'A', 'I', 'R', 'E', 'D'),
 ('AIRER', 'A', 'I', 'R', 'E', 'R'),
 ('AIRNS', 'A', 'I', 'R', 'N', 'S'),
 ('AIRTH', 'A', 'I', 'R', 'T', 'H'),
 ('AIRTS', 'A', 'I', 'R', 'T', 'S'),
 ('AISLE', 'A', 'I', 'S', 'L', 'E'),
 ('AITCH', 'A', 'I', 'T', 'C', 'H'),
 ('AITUS', 'A', 'I', 'T', 'U', 'S'),
 ('AIVER', 'A', 'I', 'V', 'E', 'R'),
 ('AIYEE', 'A', 'I', 'Y', 'E', 'E'),
 ('AIZLE', 'A', 'I', 'Z', 'L', 'E'),
 ('AJIES', 'A', 'J', 'I', 'E', 'S'),
 ('AJIVA', 'A', 'J', 'I', 'V', 'A'),
 ('AJUGA', 'A', 'J', 'U', 'G', 'A'),
 ('AJWAN', 'A', 'J', 'W', 'A', 'N'),
 ('AKEES', 'A', 'K', 'E', 'E', 'S'),
 ('AKELA', 'A', 'K', 'E', 'L', 'A'),
 ('AKENE', 'A', 'K', 'E', 'N', 'E'),
 ('AKING', 'A', 'K', 'I', 'N', 'G'),
 ('AKITA', 'A', 'K', 'I', 'T', 'A'),
 ('AKKAS', 'A', 'K', 'K', 'A', 'S'),
 ('ALAAP', 'A', 'L', 'A', 'A', 'P'),
 ('ALACK', 'A', 'L', 'A', 'C', 'K'),
 ('ALAMO', 'A', 'L', 'A', 'M', 'O'),
 ('ALAND', 'A', 'L', 'A', 'N', 'D'),
 ('ALANE', 'A', 'L', 'A', 'N', 'E'),
 ('ALANG', 'A', 'L', 'A', 'N', 'G'),
 ('ALANS', 'A', 'L', 'A', 'N', 'S'),
 ('ALANT', 'A', 'L', 'A', 'N', 'T'),
 ('ALAPA', 'A', 'L', 'A', 'P', 'A'),
 ('ALAPS', 'A', 'L', 'A', 'P', 'S'),
 ('ALARM', 'A', 'L', 'A', 'R', 'M'),
 ('ALARY', 'A', 'L', 'A', 'R', 'Y'),
 ('ALATE', 'A', 'L', 'A', 'T', 'E'),
 ('ALAYS', 'A', 'L', 'A', 'Y', 'S'),
 ('ALBAS', 'A', 'L', 'B', 'A', 'S'),
 ('ALBEE', 'A', 'L', 'B', 'E', 'E'),
 ('ALBUM', 'A', 'L', 'B', 'U', 'M'),
 ('ALCID', 'A', 'L', 'C', 'I', 'D'),
 ('ALCOS', 'A', 'L', 'C', 'O', 'S'),
 ('ALDEA', 'A', 'L', 'D', 'E', 'A'),
 ('ALDER', 'A', 'L', 'D', 'E', 'R'),
 ('ALDOL', 'A', 'L', 'D', 'O', 'L'),
 ('ALECK', 'A', 'L', 'E', 'C', 'K'),
 ('ALECS', 'A', 'L', 'E', 'C', 'S'),
 ('ALEFS', 'A', 'L', 'E', 'F', 'S'),
 ('ALEFT', 'A', 'L', 'E', 'F', 'T'),
 ('ALEPH', 'A', 'L', 'E', 'P', 'H'),
 ('ALERT', 'A', 'L', 'E', 'R', 'T'),
 ('ALEWS', 'A', 'L', 'E', 'W', 'S'),
 ('ALEYE', 'A', 'L', 'E', 'Y', 'E'),
 ('ALFAS', 'A', 'L', 'F', 'A', 'S'),
 ('ALGAE', 'A', 'L', 'G', 'A', 'E'),
 ('ALGAL', 'A', 'L', 'G', 'A', 'L'),
 ('ALGAS', 'A', 'L', 'G', 'A', 'S'),
 ('ALGID', 'A', 'L', 'G', 'I', 'D'),
 ('ALGIN', 'A', 'L', 'G', 'I', 'N'),
 ('ALGOR', 'A', 'L', 'G', 'O', 'R'),
 ('ALGUM', 'A', 'L', 'G', 'U', 'M'),
 ('ALIAS', 'A', 'L', 'I', 'A', 'S'),
 ('ALIBI', 'A', 'L', 'I', 'B', 'I'),
 ('ALIEN', 'A', 'L', 'I', 'E', 'N'),
 ('ALIFS', 'A', 'L', 'I', 'F', 'S'),
 ('ALIGN', 'A', 'L', 'I', 'G', 'N'),
 ('ALIKE', 'A', 'L', 'I', 'K', 'E'),
 ('ALINE', 'A', 'L', 'I', 'N', 'E'),
 ('ALIST', 'A', 'L', 'I', 'S', 'T'),
 ('ALIVE', 'A', 'L', 'I', 'V', 'E'),
 ('ALIYA', 'A', 'L', 'I', 'Y', 'A'),
 ('ALKIE', 'A', 'L', 'K', 'I', 'E'),
 ('ALKOS', 'A', 'L', 'K', 'O', 'S'),
 ('ALKYD', 'A', 'L', 'K', 'Y', 'D'),
 ('ALKYL', 'A', 'L', 'K', 'Y', 'L'),
 ('ALLAY', 'A', 'L', 'L', 'A', 'Y'),
 ('ALLEE', 'A', 'L', 'L', 'E', 'E'),
 ('ALLEL', 'A', 'L', 'L', 'E', 'L'),
 ('ALLEY', 'A', 'L', 'L', 'E', 'Y'),
 ('ALLIS', 'A', 'L', 'L', 'I', 'S'),
 ('ALLOD', 'A', 'L', 'L', 'O', 'D'),
 ('ALLOT', 'A', 'L', 'L', 'O', 'T'),
 ('ALLOW', 'A', 'L', 'L', 'O', 'W'),
 ('ALLOY', 'A', 'L', 'L', 'O', 'Y'),
 ('ALLYL', 'A', 'L', 'L', 'Y', 'L'),
 ('ALMAH', 'A', 'L', 'M', 'A', 'H'),
 ('ALMAS', 'A', 'L', 'M', 'A', 'S'),
 ('ALMEH', 'A', 'L', 'M', 'E', 'H'),
 ('ALMES', 'A', 'L', 'M', 'E', 'S'),
 ('ALMUD', 'A', 'L', 'M', 'U', 'D'),
 ('ALMUG', 'A', 'L', 'M', 'U', 'G'),
 ('ALODS', 'A', 'L', 'O', 'D', 'S'),
 ('ALOED', 'A', 'L', 'O', 'E', 'D'),
 ('ALOES', 'A', 'L', 'O', 'E', 'S'),
 ('ALOFT', 'A', 'L', 'O', 'F', 'T'),
 ('ALOHA', 'A', 'L', 'O', 'H', 'A'),
 ('ALOIN', 'A', 'L', 'O', 'I', 'N'),
 ('ALONE', 'A', 'L', 'O', 'N', 'E'),
 ('ALONG', 'A', 'L', 'O', 'N', 'G'),
 ('ALOOF', 'A', 'L', 'O', 'O', 'F'),
 ('ALOOS', 'A', 'L', 'O', 'O', 'S'),
 ('ALOUD', 'A', 'L', 'O', 'U', 'D'),
 ('ALOWE', 'A', 'L', 'O', 'W', 'E'),
 ('ALPHA', 'A', 'L', 'P', 'H', 'A'),
 ('ALTAR', 'A', 'L', 'T', 'A', 'R'),
 ('ALTER', 'A', 'L', 'T', 'E', 'R'),
 ('ALTHO', 'A', 'L', 'T', 'H', 'O'),
 ('ALTOS', 'A', 'L', 'T', 'O', 'S'),
 ('ALULA', 'A', 'L', 'U', 'L', 'A'),
 ('ALUMS', 'A', 'L', 'U', 'M', 'S'),
 ('ALURE', 'A', 'L', 'U', 'R', 'E'),
 ('ALVAR', 'A', 'L', 'V', 'A', 'R'),
 ('ALWAY', 'A', 'L', 'W', 'A', 'Y'),
 ('AMAHS', 'A', 'M', 'A', 'H', 'S'),
 ('AMAIN', 'A', 'M', 'A', 'I', 'N'),
 ('AMASS', 'A', 'M', 'A', 'S', 'S'),
 ('AMATE', 'A', 'M', 'A', 'T', 'E'),
 ('AMAUT', 'A', 'M', 'A', 'U', 'T'),
 ('AMAZE', 'A', 'M', 'A', 'Z', 'E'),
 ('AMBAN', 'A', 'M', 'B', 'A', 'N'),
 ('AMBER', 'A', 'M', 'B', 'E', 'R'),
 ('AMBIT', 'A', 'M', 'B', 'I', 'T'),
 ('AMBLE', 'A', 'M', 'B', 'L', 'E'),
 ('AMBOS', 'A', 'M', 'B', 'O', 'S'),
 ('AMBRY', 'A', 'M', 'B', 'R', 'Y'),
 ('AMEBA', 'A', 'M', 'E', 'B', 'A'),
 ('AMEER', 'A', 'M', 'E', 'E', 'R'),
 ('AMEND', 'A', 'M', 'E', 'N', 'D'),
 ('AMENE', 'A', 'M', 'E', 'N', 'E'),
 ('AMENS', 'A', 'M', 'E', 'N', 'S'),
 ('AMENT', 'A', 'M', 'E', 'N', 'T'),
 ('AMIAS', 'A', 'M', 'I', 'A', 'S'),
 ('AMICE', 'A', 'M', 'I', 'C', 'E'),
 ('AMICI', 'A', 'M', 'I', 'C', 'I'),
 ('AMIDE', 'A', 'M', 'I', 'D', 'E'),
 ('AMIDO', 'A', 'M', 'I', 'D', 'O'),
 ('AMIDS', 'A', 'M', 'I', 'D', 'S'),
 ('AMIES', 'A', 'M', 'I', 'E', 'S'),
 ('AMIGA', 'A', 'M', 'I', 'G', 'A'),
 ('AMIGO', 'A', 'M', 'I', 'G', 'O'),
 ('AMINE', 'A', 'M', 'I', 'N', 'E'),
 ('AMINO', 'A', 'M', 'I', 'N', 'O'),
 ('AMINS', 'A', 'M', 'I', 'N', 'S'),
 ('AMIRS', 'A', 'M', 'I', 'R', 'S'),
 ('AMISS', 'A', 'M', 'I', 'S', 'S'),
 ('AMITY', 'A', 'M', 'I', 'T', 'Y'),
 ('AMLAS', 'A', 'M', 'L', 'A', 'S'),
 ('AMMAN', 'A', 'M', 'M', 'A', 'N'),
 ('AMMON', 'A', 'M', 'M', 'O', 'N'),
 ('AMMOS', 'A', 'M', 'M', 'O', 'S'),
 ('AMNIA', 'A', 'M', 'N', 'I', 'A'),
 ('AMNIC', 'A', 'M', 'N', 'I', 'C'),
 ('AMNIO', 'A', 'M', 'N', 'I', 'O'),
 ('AMOKS', 'A', 'M', 'O', 'K', 'S'),
 ('AMOLE', 'A', 'M', 'O', 'L', 'E'),
 ('AMONG', 'A', 'M', 'O', 'N', 'G'),
 ('AMORT', 'A', 'M', 'O', 'R', 'T'),
 ('AMOUR', 'A', 'M', 'O', 'U', 'R'),
 ('AMOVE', 'A', 'M', 'O', 'V', 'E'),
 ('AMOWT', 'A', 'M', 'O', 'W', 'T'),
 ('AMPED', 'A', 'M', 'P', 'E', 'D'),
 ('AMPLE', 'A', 'M', 'P', 'L', 'E'),
 ('AMPLY', 'A', 'M', 'P', 'L', 'Y'),
 ('AMPUL', 'A', 'M', 'P', 'U', 'L'),
 ('AMRIT', 'A', 'M', 'R', 'I', 'T'),
 ('AMUCK', 'A', 'M', 'U', 'C', 'K'),
 ('AMUSE', 'A', 'M', 'U', 'S', 'E'),
 ('AMYLS', 'A', 'M', 'Y', 'L', 'S'),
 ('ANANA', 'A', 'N', 'A', 'N', 'A'),
 ('ANATA', 'A', 'N', 'A', 'T', 'A'),
 ('ANCHO', 'A', 'N', 'C', 'H', 'O'),
 ('ANCLE', 'A', 'N', 'C', 'L', 'E'),
 ('ANCON', 'A', 'N', 'C', 'O', 'N'),
 ('ANDRO', 'A', 'N', 'D', 'R', 'O'),
 ('ANEAR', 'A', 'N', 'E', 'A', 'R'),
 ('ANELE', 'A', 'N', 'E', 'L', 'E'),
 ('ANENT', 'A', 'N', 'E', 'N', 'T'),
 ('ANGAS', 'A', 'N', 'G', 'A', 'S'),
 ('ANGEL', 'A', 'N', 'G', 'E', 'L'),
 ('ANGER', 'A', 'N', 'G', 'E', 'R'),
 ('ANGLE', 'A', 'N', 'G', 'L', 'E'),
 ('ANGLO', 'A', 'N', 'G', 'L', 'O'),
 ('ANGRY', 'A', 'N', 'G', 'R', 'Y'),
 ('ANGST', 'A', 'N', 'G', 'S', 'T'),
 ('ANIGH', 'A', 'N', 'I', 'G', 'H'),
 ('ANILE', 'A', 'N', 'I', 'L', 'E'),
 ('ANILS', 'A', 'N', 'I', 'L', 'S'),
 ('ANIMA', 'A', 'N', 'I', 'M', 'A'),
 ('ANIME', 'A', 'N', 'I', 'M', 'E'),
 ('ANIMI', 'A', 'N', 'I', 'M', 'I'),
 ('ANION', 'A', 'N', 'I', 'O', 'N'),
 ('ANISE', 'A', 'N', 'I', 'S', 'E'),
 ('ANKER', 'A', 'N', 'K', 'E', 'R'),
 ('ANKHS', 'A', 'N', 'K', 'H', 'S'),
 ('ANKLE', 'A', 'N', 'K', 'L', 'E'),
 ('ANKUS', 'A', 'N', 'K', 'U', 'S'),
 ('ANLAS', 'A', 'N', 'L', 'A', 'S'),
 ('ANNAL', 'A', 'N', 'N', 'A', 'L'),
 ('ANNAS', 'A', 'N', 'N', 'A', 'S'),
 ('ANNAT', 'A', 'N', 'N', 'A', 'T'),
 ('ANNEX', 'A', 'N', 'N', 'E', 'X'),
 ('ANNOY', 'A', 'N', 'N', 'O', 'Y'),
 ('ANNUL', 'A', 'N', 'N', 'U', 'L'),
 ('ANOAS', 'A', 'N', 'O', 'A', 'S'),
 ('ANODE', 'A', 'N', 'O', 'D', 'E'),
 ('ANOLE', 'A', 'N', 'O', 'L', 'E'),
 ('ANOMY', 'A', 'N', 'O', 'M', 'Y'),
 ('ANSAE', 'A', 'N', 'S', 'A', 'E'),
 ('ANTAE', 'A', 'N', 'T', 'A', 'E'),
 ('ANTAR', 'A', 'N', 'T', 'A', 'R'),
 ('ANTAS', 'A', 'N', 'T', 'A', 'S'),
 ('ANTED', 'A', 'N', 'T', 'E', 'D'),
 ('ANTES', 'A', 'N', 'T', 'E', 'S'),
 ('ANTIC', 'A', 'N', 'T', 'I', 'C'),
 ('ANTIS', 'A', 'N', 'T', 'I', 'S'),
 ('ANTRA', 'A', 'N', 'T', 'R', 'A'),
 ('ANTRE', 'A', 'N', 'T', 'R', 'E'),
 ('ANTSY', 'A', 'N', 'T', 'S', 'Y'),
 ('ANURA', 'A', 'N', 'U', 'R', 'A'),
 ('ANVIL', 'A', 'N', 'V', 'I', 'L'),
 ('ANYON', 'A', 'N', 'Y', 'O', 'N'),
 ('AORTA', 'A', 'O', 'R', 'T', 'A'),
 ('APACE', 'A', 'P', 'A', 'C', 'E'),
 ('APAGE', 'A', 'P', 'A', 'G', 'E'),
 ('APAID', 'A', 'P', 'A', 'I', 'D'),
 ('APART', 'A', 'P', 'A', 'R', 'T'),
 ('APAYD', 'A', 'P', 'A', 'Y', 'D'),
 ('APAYS', 'A', 'P', 'A', 'Y', 'S'),
 ('APEAK', 'A', 'P', 'E', 'A', 'K'),
 ('APEEK', 'A', 'P', 'E', 'E', 'K'),
 ('APERS', 'A', 'P', 'E', 'R', 'S'),
 ('APERT', 'A', 'P', 'E', 'R', 'T'),
 ('APERY', 'A', 'P', 'E', 'R', 'Y'),
 ('APGAR', 'A', 'P', 'G', 'A', 'R'),
 ('APHID', 'A', 'P', 'H', 'I', 'D'),
 ('APHIS', 'A', 'P', 'H', 'I', 'S'),
 ('APIAN', 'A', 'P', 'I', 'A', 'N'),
 ('APING', 'A', 'P', 'I', 'N', 'G'),
 ('APIOL', 'A', 'P', 'I', 'O', 'L'),
 ('APISH', 'A', 'P', 'I', 'S', 'H'),
 ('APISM', 'A', 'P', 'I', 'S', 'M'),
 ('APNEA', 'A', 'P', 'N', 'E', 'A'),
 ('APODE', 'A', 'P', 'O', 'D', 'E'),
 ('APODS', 'A', 'P', 'O', 'D', 'S'),
 ('APOOP', 'A', 'P', 'O', 'O', 'P'),
 ('APORT', 'A', 'P', 'O', 'R', 'T'),
 ('APPAL', 'A', 'P', 'P', 'A', 'L'),
 ('APPAY', 'A', 'P', 'P', 'A', 'Y'),
 ('APPEL', 'A', 'P', 'P', 'E', 'L'),
 ('APPLE', 'A', 'P', 'P', 'L', 'E'),
 ('APPLY', 'A', 'P', 'P', 'L', 'Y'),
 ('APPRO', 'A', 'P', 'P', 'R', 'O'),
 ('APPUI', 'A', 'P', 'P', 'U', 'I'),
 ('APPUY', 'A', 'P', 'P', 'U', 'Y'),
 ('APRES', 'A', 'P', 'R', 'E', 'S'),
 ('APRON', 'A', 'P', 'R', 'O', 'N'),
 ('APSES', 'A', 'P', 'S', 'E', 'S'),
 ('APSIS', 'A', 'P', 'S', 'I', 'S'),
 ('APSOS', 'A', 'P', 'S', 'O', 'S'),
 ('APTED', 'A', 'P', 'T', 'E', 'D'),
 ('APTER', 'A', 'P', 'T', 'E', 'R'),
 ('APTLY', 'A', 'P', 'T', 'L', 'Y'),
 ('AQUAE', 'A', 'Q', 'U', 'A', 'E'),
 ('AQUAS', 'A', 'Q', 'U', 'A', 'S'),
 ('ARABA', 'A', 'R', 'A', 'B', 'A'),
 ('ARAKS', 'A', 'R', 'A', 'K', 'S'),
 ('ARAME', 'A', 'R', 'A', 'M', 'E'),
 ('ARARS', 'A', 'R', 'A', 'R', 'S'),
 ('ARBAS', 'A', 'R', 'B', 'A', 'S'),
 ('ARBOR', 'A', 'R', 'B', 'O', 'R'),
 ('ARCED', 'A', 'R', 'C', 'E', 'D'),
 ('ARCHI', 'A', 'R', 'C', 'H', 'I'),
 ('ARCOS', 'A', 'R', 'C', 'O', 'S'),
 ('ARCUS', 'A', 'R', 'C', 'U', 'S'),
 ('ARDEB', 'A', 'R', 'D', 'E', 'B'),
 ('ARDOR', 'A', 'R', 'D', 'O', 'R'),
 ('ARDRI', 'A', 'R', 'D', 'R', 'I'),
 ('AREAD', 'A', 'R', 'E', 'A', 'D'),
 ('AREAE', 'A', 'R', 'E', 'A', 'E'),
 ('AREAL', 'A', 'R', 'E', 'A', 'L'),
 ('AREAR', 'A', 'R', 'E', 'A', 'R'),
 ('AREAS', 'A', 'R', 'E', 'A', 'S'),
 ('ARECA', 'A', 'R', 'E', 'C', 'A'),
 ('AREDD', 'A', 'R', 'E', 'D', 'D'),
 ('AREDE', 'A', 'R', 'E', 'D', 'E'),
 ('AREFY', 'A', 'R', 'E', 'F', 'Y'),
 ('AREIC', 'A', 'R', 'E', 'I', 'C'),
 ('ARENA', 'A', 'R', 'E', 'N', 'A'),
 ('ARENE', 'A', 'R', 'E', 'N', 'E'),
 ('AREPA', 'A', 'R', 'E', 'P', 'A'),
 ('ARERE', 'A', 'R', 'E', 'R', 'E'),
 ('ARETE', 'A', 'R', 'E', 'T', 'E'),
 ('ARETS', 'A', 'R', 'E', 'T', 'S'),
 ('ARETT', 'A', 'R', 'E', 'T', 'T'),
 ('ARGAL', 'A', 'R', 'G', 'A', 'L'),
 ('ARGAN', 'A', 'R', 'G', 'A', 'N'),
 ('ARGIL', 'A', 'R', 'G', 'I', 'L'),
 ('ARGLE', 'A', 'R', 'G', 'L', 'E'),
 ('ARGOL', 'A', 'R', 'G', 'O', 'L'),
 ('ARGON', 'A', 'R', 'G', 'O', 'N'),
 ('ARGOT', 'A', 'R', 'G', 'O', 'T'),
 ('ARGUE', 'A', 'R', 'G', 'U', 'E'),
 ('ARGUS', 'A', 'R', 'G', 'U', 'S'),
 ('ARHAT', 'A', 'R', 'H', 'A', 'T'),
 ('ARIAS', 'A', 'R', 'I', 'A', 'S'),
 ('ARIEL', 'A', 'R', 'I', 'E', 'L'),
 ('ARIKI', 'A', 'R', 'I', 'K', 'I'),
 ('ARILS', 'A', 'R', 'I', 'L', 'S'),
 ('ARIOT', 'A', 'R', 'I', 'O', 'T'),
 ('ARISE', 'A', 'R', 'I', 'S', 'E'),
 ('ARISH', 'A', 'R', 'I', 'S', 'H'),
 ('ARKED', 'A', 'R', 'K', 'E', 'D'),
 ('ARLED', 'A', 'R', 'L', 'E', 'D'),
 ('ARLES', 'A', 'R', 'L', 'E', 'S'),
 ('ARMED', 'A', 'R', 'M', 'E', 'D'),
 ('ARMER', 'A', 'R', 'M', 'E', 'R'),

In [39]:
words_df = pd.DataFrame.from_records(char_tuples, columns=["word", "l1", "l2", "l3", "l4", "l5"])
words_df

        word l1 l2 l3 l4 l5
0      AAHED  A  A  H  E  D
1      AALII  A  A  L  I  I
2      AARGH  A  A  R  G  H
3      AARTI  A  A  R  T  I
4      ABACA  A  B  A  C  A
...      ... .. .. .. .. ..
12915  ZUZIM  Z  U  Z  I  M
12916  ZYGAL  Z  Y  G  A  L
12917  ZYGON  Z  Y  G  O  N
12918  ZYMES  Z  Y  M  E  S
12919  ZYMIC  Z  Y  M  I  C

[12920 rows x 6 columns]

In [40]:
endsWithS = words_df[words_df["l5"]=='S'].count()["l5"]
everythingElse = words_df.count()["l1"]

In [41]:
endsWithS / everythingElse

np.float64(0.30534055727554177)

In [42]:
words_df[(words_df["l4"] == "E") & (words_df["l5"] == "S")]

        word l1 l2 l3 l4 l5
19     ABBES  A  B  B  E  S
30     ABIES  A  B  I  E  S
33     ABLES  A  B  L  E  S
59     ABYES  A  B  Y  E  S
71     ACHES  A  C  H  E  S
...      ... .. .. .. .. ..
12849  ZEXES  Z  E  X  E  S
12850  ZEZES  Z  E  Z  E  S
12865  ZINES  Z  I  N  E  S
12893  ZONES  Z  O  N  E  S
12918  ZYMES  Z  Y  M  E  S

[723 rows x 6 columns]